# -*- coding: utf-8 -*-
"""trainingscriptINSTRUERE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFMnRHUrDCnqn69S7-S678UwAW78c4qQ
"""

!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps trl peft accelerate bitsandbytes
!pip install xformers==0.0.27
!pip install triton
!pip install datasets
!pip install huggingface_hub

# Importing the necessary dependencies

import torch
major_version, minor_version = torch.cuda.get_device_capability()

# Importing the model
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# Loading the llama3 model as the inference model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/llama-3-8b-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

# Importing the Supervised Fintuning Trainer
from trl import SFTTrainer
from transformers import TrainingArguments
from datasets import load_dataset
max_seq_length = 2048

# url = "https://huggingface.co/datasets/laion/OIG/resolve/main/unified_chip2.jsonl"
# # Loading the dataset from the hugging face repository
# dataset = load_dataset("json", data_files = {"train" : url}, split = "train")

dataset = load_dataset("DEEPAK70681/CryptoSendIntentv2", split = "train")

print(dataset[:5])

def generate_text(text):
    inputs = tokenizer(text, return_tensors="pt").to("cuda:0")
    outputs = model.generate(**inputs, max_new_tokens=100)
    print(tokenizer.decode(outputs[0], skip_special_tokens=True))

# Test Pre-train:
print("Before training\n")
FastLanguageModel.for_inference(model)
generate_text("Send 0.25 BTC to 0xdBA0578eAE8406D32ad5Ed362A24e63893535a5e")

# 4. Do model patching and add fast LoRA weights and training
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 16,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    use_gradient_checkpointing = True,
    random_state = 3407,
    max_seq_length = max_seq_length,
    use_rslora = False,  # Rank stabilized LoRA
    loftq_config = None, # LoftQ
)
# 5. using the supervised fine tuning trainer to fine tune the model
trainer = SFTTrainer(
    model = model,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    tokenizer = tokenizer,
    args = TrainingArguments(
        per_device_train_batch_size=8,  # Increase batch size if memory permits
        gradient_accumulation_steps=2,  # Adjust based on batch size
        warmup_steps=100,               # Increased warmup steps
        max_steps=1,                  # Increased steps for better results like 250 for best, 60 for average performance
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        logging_steps=10,               # Adjusted logging frequency
        output_dir="outputs",
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,

    ),
)
trainer.train()

# Test after training
print("\n ######## \nAfter training\n")
FastLanguageModel.for_inference(model)
generate_text("<|begin_of_text|><|start_header_id|>user<|end_header_id|>Send 59 CPX to 0x1a2B3c4D5E6F7G8H9I0J1K2L3M4N5O6P7Q8R9STU<|eot_id|>")

model.save_pretrained("sendIntentModelTHEOGv1")

# Log in using your Hugging Face token
from huggingface_hub import login

# Enter your token here
login(token="your_huggingface_token_here")
# 

model.push_to_hub("DEEPAK70681/NewFinetunedModel") #put your repo name here as your token can config your repos

model_repo_id = "DEEPAK70681/NewFinetunedModel" #put your repo name here as your token can config your repos

print(model_repo_id)

